clientScripts method added
DevExpress/angular-testcafe pull request #84
Opened 2022-05-20 00:39 UTC by fixedmichal

clientScripts method added

2022-05-23 07:51 UTC, miherlosev requested changes
Thank you for your contribution to TestCafe. I left a few minor remarks.

2022-05-23 07:51 UTC, miherlosev commented on src/testcafe/schema.d.ts
> +    clientScripts?: string | string[];
Please copy the typing from [here](https://github.com/DevExpress/testcafe/blob/cde211fd164938e0db0a29c7ede17fc473d6fdf1/ts-defs-src/runner-api/runner-api.d.ts#L146).

2022-05-23 07:51 UTC, miherlosev commented on src/testcafe/testcafe.builder.ts
> +        .clientScripts(opts.clientScripts instanceof Array ? opts.clientScripts : [ opts.clientScripts ])
You can simplify code as `.clientScripts(opts.clientScripts)`

2022-07-13 07:06 UTC, closed without merging

2022-07-13 07:11 UTC, AndreyBelym commented
I accidentally pushed the upstream `master` into the fork, so GitHub closed the PR automatically due to no differences between the PR and `master`. And since I cannot reopen it, let's continue working on this feature in #88.